# Generated by Django 4.1 on 2023-03-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='End_Time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Start_Time',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
